---
title: "Founder Diet Study Data"
author: "Brian Yandell"
date: "2022-12-05"
output: html_document
params:
  dataset:
    label: "Measurement Set"
    value: plasma
    input: select
    choices: [physio, plasma, liver]
  traits:
    label: "Number of traits"
    value: 2
    input: slider
    min: 2
    max: 6
    
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      comment = "", fig.width = 7, fig.height = 7)
```

```{r}
library(tidyverse)
library(readxl)
library(readr)
```

```{r}
meas <- readRDS(paste0(params$dataset, ".rds"))
measum <- readRDS("traitsum.rds") %>%
  filter(datatype == params$dataset) %>%
  arrange(strain.sex.diet)
```

```{r}
traits <- measum$trait[seq_len(as.integer(params$traits))]
meas <- meas %>% 
  filter(trait %in% traits)
```

Here we pick out 6 compounds with the lowest absolute value and compares sex, diet and strain.

```{r warnings = FALSE}
ggplot(meas %>%
         unite(sex_diet, sex, diet)) +
  aes(sex_diet, value, col = sex_diet) +
  geom_jitter() +
  facet_grid(trait ~ strain, scales = "free_y") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r}
dat <- meas %>%
        select(strain, number, sex, diet, trait, value) %>%
        pivot_wider(names_from = "trait", values_from = "value")
load("data/CCcolors.RData")
plotly::ggplotly(
  ggplot(dat) +
    aes(.data[[traits[1]]], .data[[traits[2]]], color = strain) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_point(size = 2) +
    scale_color_manual(values = CCcolors) +
    facet_grid(sex ~ diet)) 
```
