---
title: "Time Measurements"
author: "Brian Yandell"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
params:
  echo: no
  rootdir: /mnt/researchdrive/adattie/General/founder_diet_study
---

```{r}
rawdir <- file.path(params$rootdir, "RawData")
harmonizeddir <- file.path(params$rootdir, "HarmonizedData")
```

```{r include = FALSE}
knitr::opts_chunk$set(echo = params$echo, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = params$rootdir)
```

# Traits over time

```{r}
traitData <- readRDS(file.path(harmonizeddir, "Normalized", "traitData.rds"))
traitSignal <- readRDS(file.path(harmonizeddir, "Normalized", "traitSignal.rds"))
traitStats <- readRDS(file.path(harmonizeddir, "Normalized", "traitStats.rds"))
```

```{r}
dtraits <- foundr::timetraits(traitSignal, "week")
```

```{r}
traitTime <- foundr::traitTimes(traitData, traitSignal,
                           "Physio: BW",
                           "cellmean", "week")
```

```{r}
print(plot(traitTime))
```

```{r}
traitTime <- foundr::traitTimes(traitData, traitSignal,
                           c("Physio: BW", "Physio: BL"),
                           "cellmean", "week")
```

```{r}
print(foundr::ggplot_traitTimes(traitTime, facet_strain = TRUE))
```

```{r}
p1 <- foundr::ggplot_traitTimes(traitTime,
  facet_strain = TRUE)
print(p1)
```

## Stats

```{r}
traitSum <- foundr::traitTimes(traitStats,
                           c("Physio: BW", "Physio: BL"),
                           "p.value", "week", "terms")
```

```{r}
p2 <- foundr::ggplot_traitTimes(traitSum, span = 0.75)
print(p2)
```

```{r}
cowplot::plot_grid(p1,p2, ncol = 2)
```

```{r}
timetable <- function(object) {
  class(object) <- "list"
  for(i in names(object)) {
    object[[i]] <- as.data.frame(
      tidyr::separate_wider_delim(
        dplyr::select(
          dplyr::mutate(
            dplyr::rename(
              object[[i]], 
              p.value = i),
            p.value = signif(10 ^ -p.value, 4)),
          -strain),
        datatraits,
        delim = ": ",
        names = c("dataset", "trait")))
  }
  dplyr::as_tibble(
    dplyr::bind_rows(
      object))
}
```

```{r}
dplyr::filter(
  dplyr::arrange(
    timetable(traitSum),
    p.value),
  (term %in% c("strain:diet", "strain:sex:diet")),
  p.value < .2)
```

## Stats Summaries

```{r}
traitTime <- foundr::traitTimes(traitData, traitSignal,
                           c("Physio: BW"),
                           "value", "week_summary")
```

```{r}
p1 <- foundr::ggplot_traitTimes(traitTime,
  facet_strain = FALSE)
print(p1)
```

```{r}
p1 <- foundr::ggplot_traitTimes(traitTime,
  facet_strain = TRUE)
print(p1)
```


```{r}
traitSum <- foundr::traitTimes(traitStats,
                           c("Physio: BW", "Physio: BL"),
                           "p.value", "week_summary", "terms")
```

```{r}
p2 <- foundr::ggplot_traitTimes(traitSum)
print(p2)
```


```{r}
cowplot::plot_grid(p1,p2, ncol = 2)
```

```{r}
traittbl <- timetable(traitSum)
```

```{r}
p1 <- foundr::ggplot_traitTimes(traitTime,
  facet_strain = FALSE)
cowplot::plot_grid(p1,p2, ncol = 2)
```

```{r}
plot(foundr::traitSolos(traitData, traitSignal, "Physio: BW_Slope"))
```

