---
title: "vivo_clean"
output: html_document
date: "2023-07-12"
params:
  echo: no
  rootdir: Z:/General/founder_diet_study

---

```{r}
library(tidyr)
library(readxl)
library(tidyverse)
library(foundr)

```

```{r}
harmonizeddir <- file.path(params$rootdir, "HarmonizedData")
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = harmonizeddir)
```

```{r}
harmonizeddir <- "."
rawdir <- "../RawData"
getwd()
```
```{r}
rawdir<-"Z:/General/founder_diet_study"
links <- read.csv(file.path("..", "RawData", "source.csv"), fill = TRUE) %>%
  mutate(address = file.path(rawdir, address))

```

```{r}
PhysioHarmony <- function(dataset,...,rename_ketoneBodies) {

  filename <- linkpath(dataset, links)

  # Data are in sheet 2 starting on line 1
  out <- read_excel(filename, sheet = 2) %>%
  
  # Rename Ketone Bodies from KB_14wk
  rename_with(
    ~ ifelse(rename_ketoneBodies, "KetoneBodies", .x),"KB_14wk" ) %>%

    # Traits begin in column 5
    pivot_longer(-(1:4), names_to = "trait", values_to = "value") %>%

    # Diets coded in file.
    mutate(diet = ifelse(as.character(diet) == "200339",
                         "HC_LF", "HF_LC")) %>%

    # Rename columns to harmonize data.
    rename(condition = "diet",
           animal = "number") %>%
    mutate(animal = as.character(animal)) %>%

    # These are harmonized columns and their names.
    select(strain, sex, animal, condition, trait, value)

  # Add area under curve traits for measurements over minutes.
  GTT <- out %>%
    filter(grepl("_[0-9]+_[0-9]+wk$", trait)) %>%
    # Separate out minutes and week.
    # Kludge to catch cpep ratio trait.
    separate_wider_delim(
      trait,
      delim = "_",
      names = c("cpep1", "cpep2", "gtt","trait","minute","week"),
      too_few = "align_end",
      too_many = "merge") %>%
    mutate(trait = ifelse(
      trait == "ratio",
      paste(cpep1, cpep2, gtt, trait, sep = "_"),
      paste(gtt, trait, sep = "_")))
    
  # Filter to traits with >1 minute measurement.
  GTTct <- GTT %>%
    distinct(trait, minute, week) %>%
    count(trait, week) %>%
    filter(n > 1)

  GTT <- GTT %>%
    filter(trait %in% GTTct$trait & week %in% GTTct$week) %>%
    # Calculate AUC and other summaries.
    area_under_curve("minute") %>%
    # Unite summary name with week.
    unite(trait, trait, week) %>%
    # Harmonize names.
    select(strain, sex, animal, condition, trait, value)
   #print(GTT)
  # Add area under curve traits for measurements over weeks.
  wks <- out %>%
    filter(grepl("_[0-9]+wk$", trait) & !grepl("_([0-9]+|tAUC|iAUC)_[0-9]+wk$", trait)) %>%
    # Kludge to use AUC routine for now by calling weeks as minutes.
    separate_wider_delim(
      trait,
      delim = "_",
      names = c("trait1","trait","week"),
      too_few = "align_end",
      too_many = "merge") %>%
    mutate(
      trait = ifelse(
        is.na(trait1),
        trait,
        paste(trait1, trait, sep = "_")),
      week = as.numeric(str_remove(week, "wk$")))

  # Filter to traits with >1 week measurement.
  wksct <- wks %>%
    distinct(trait, week) %>%
    count(trait) %>%
    filter(n > 1)

  wks <- wks %>%
    filter(trait %in% wksct$trait) %>%
    # Calculate AUC and other summaries.
    area_under_curve("week") %>%
    # Harmonize names.
    select(strain, sex, animal, condition, trait, value)

  bind_rows(out, GTT, wks)
}


```

```{r}

PhysioHarmony("vivo_founder_diet_data",links,rename_ketoneBodies =  FALSE)

```

